config/routes.rb
Rails.application.routes.draw do

  namespace :hq do
    resource :results, only: [:create]
  end

  namespace :leaderboards do
    resource :overall, only: [:create], controller: 'overall'
  end

  root 'home#index'

end

app/controllers/home_controller.rb
require 'hq/results'

class HomeController < ApplicationController

  def index

  end

end

app/helpers/home_helper.rb
module HomeHelper

  def year_select_options
    options_for_select((2011..Date.current.year).to_a.reverse)
  end

  def stage_select_options
    select_options_by_enum(HQ::Stage.all)
  end

  def division_select_options
    select_options_by_enum(HQ::Division.all)
  end

  def super_region_and_region_select_options
    super_regions = HQ::SuperRegion.all.map {|e| [e.name.titleize, e.name]}
    regions = HQ::Region.all.map {|e| [e.name.titleize, e.name]}

    grouped_options_for_select(
        'Super Region' => super_regions,
        'Region' => regions
    )
  end

  def region_select_options
    select_options_by_enum(HQ::Region.all)
  end

  def regional_event_select_options
    options = (1..7).map {|num| ["Event #{num}", num] }
    options_for_select(options)
  end

  def select_options_by_enum(enums)
    options = enums.map {|e| [e.name.titleize, e.name] }
    options_for_select(options)
  end

  def analyzed_year_select_options
    options_for_select([2015])
  end

  def scorer_options
    options_for_select([['Golf', 'golf'], ['2015 Regional', '2015_regional']])
  end

  def analyzed_super_region_select_options
    options = HQ::SuperRegion.map {|e| [e.name.titleize, e.name] }
    options.unshift(['Games Qualifiers', 'games_qualifier'])
    options.unshift(['Across Regions', 'overall'])
    options_for_select(options)
  end

end

app/views/home/index.html.haml
%h1 FloElite CFG Stats

%h2 Analyzed

%p
  These results have been analyzed within their peer group For the moment only the 2015 Regional has this information.
  If we're happy with it then we can analyze the rest of the HQ Results.

%p
  The
  %b
    Golf
  scoring method scores each event by their rank and then sorts from lowest score to highest. This is how
  Open workouts are scored and Regionals were prior to 2015. The
  %b
    2015 Regional
  scoring method is a tiered scoring method that weights higher placement according to
  = link_to 'http://games.crossfit.com/article/your-guide-regional-scoring'

%h3 Regionals

%p
  NOTE:
  %b
    2015 Regional
  cannot be used to score Across Regions because it cannot support that many people.

= form_tag leaderboards_overall_path(stage: 'regional', format: :csv), { class: '' } do

  .form-group.form-inline
    = select_tag :year, analyzed_year_select_options, { class: 'form-control' }
    = select_tag :division, division_select_options, { class: 'form-control' }
    = select_tag :region, analyzed_super_region_select_options, { class: 'form-control' }

  .form-group.form-inline
    Score using
    = select_tag :scorer, scorer_options, { class: 'form-control' }
    method

  .form-group
    = submit_tag 'Download', { class: 'btn btn-primary' }

%h2 Raw

%p
  These results are pulled directly from
  = link_to 'http://games.crossfit.com'
  and are useful if you want those in a more malleable format. These serve as the basis for the more advanced analysis
  and leaderboards provided here.

%h3 Games

= form_tag hq_results_path(stage: 'games', format: :csv), { class: 'form-inline' } do
  = select_tag :year, year_select_options, { class: 'form-control' }
  = select_tag :division, division_select_options, { class: 'form-control' }
  = submit_tag 'Download', { class: 'btn btn-primary' }

%h3 Regionals

= form_tag hq_results_path(stage: 'regional', format: :csv), { class: 'form-inline' } do
  = select_tag :year, year_select_options, { class: 'form-control' }
  = select_tag :division, division_select_options, { class: 'form-control' }
  = select_tag :region, super_region_and_region_select_options, { class: 'form-control' }
  = submit_tag 'Download', { class: 'btn btn-primary' }

%p.help-block
  Be careful to only select Super Regions for years 2015 or later.

%h3 Open

= form_tag hq_results_path(stage: 'open', format: :csv), { class: 'form-inline' } do
  .form-group
    = select_tag :year, year_select_options, { class: 'form-control' }
    = select_tag :division, division_select_options, { class: 'form-control' }
    = select_tag :region, region_select_options, { class: 'form-control' }
    = submit_tag 'Download', { class: 'btn btn-primary' }